title: Heather M. Kopp
author: Heather M. Kopp
email: hmk439@mail.missouri.edu
scholar_userid: u6EcVJoAAAAJ
orcid_id: 0000-0003-2606-7089
twitter_username: hmkopp6
github_username: heatherkopp
work_url: https://truman.missouri.edu/people/kopp

markdown: kramdown
theme: minima 
  skin: dark 
