title: Heather M. Kopp
author: Heather M. Kopp
email: hmk439@mail.missouri.edu 

scholar_username: u6EcVJoAAAAJ
platform: google_scholar, user_url: "https://scholar.google.com/citations?user=u6EcVJoAAAAJ" 
#orcid_id: 0000-0003-2606-7089
twitter_username: hmkopp6
github_username: heatherkopp
url: https://truman.missouri.edu/people/kopp

markdown: kramdown
theme: minima 
