title: Heather M. Kopp
author: Heather M. Kopp
email: hmk439@mail.missouri.edu 
website:  https://truman.missouri.edu/people/kopp

minima:
  skin: auto
  social_links:
  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=u6EcVJoAAAAJ" }
  - { platform: orcid, user_url: "https://orcid.org/0000-0003-2606-7089" }
  - { platform: github, user_url: "https://github.com/heatherkopp" }
  - { platform: twitter, user_url: "https://twitter.com/hmkopp6" }

#url: https://truman.missouri.edu/people/kopp

markdown: kramdown
theme: minima 
